name = "proud-sound-77a5"
main = "src/index.js"
compatibility_date = "2024-09-23"
workers_dev = true

[[durable_objects.bindings]]
name = "CHAT_ROOM"
class_name = "ChatRoom"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["ChatRoom"]

# ===== متغيرات البيئة =====
[vars]
OWNER_USERNAME = "maalek_1234"
OWNER_TOKEN = "T1!7#Lm9$Vx2@Plz8%RL4&/n6*Bw3^Cd5"
